import '../../models/root_app.dart';

const List<RootApp> rootAppsList = [
  RootApp(
    title: 'Shamiko',
    description: 'A Zygisk module to hide Magisk root from applications that perform deep filesystem security scans.',
    category: 'Security & Privacy',
    whatIsIt: 'A kernel-level root hiding helper module that runs inside Zygisk (Zygote process injection).',
    whyRoot: 'It intercepts dynamic security calls before apps can query the su binaries, hiding the root framework entirely.',
    communityPraise: 'Highly praised as the standard tool for bypassing root checks. Unlike native DenyList, Shamiko operates in hiding mode without blocking app processes.',
    linkUrl: 'https://github.com/LSPosed/Lishumi/releases',
    iconName: 'security',
  ),
  RootApp(
    title: 'Obtainium',
    description: 'An open-source package manager that lets you install and update applications directly from their source repositories.',
    category: 'Package Managers',
    whatIsIt: 'An application installer that fetches and checks updates directly from GitHub releases, GitLab, or raw HTML links.',
    whyRoot: 'Requires root to execute silent, background, unattended package installations and upgrades without manual confirmation screens.',
    communityPraise: 'Deeply praised by power users for removing the middleman (Google Play/F-Droid stores). You get raw compiled FOSS tools straight from developer releases.',
    linkUrl: 'https://github.com/ImranR98/Obtainium',
    iconName: 'shop',
  ),
  RootApp(
    title: 'Thanox',
    description: 'A comprehensive battery saver, background freeze controller, and standby manager (spiritual successor to Greenify).',
    category: 'Performance Tuning',
    whatIsIt: 'An advanced system optimizer that manages application startup and lifecycle behaviors.',
    whyRoot: 'Hooks into the OS Activity Manager Service using root to forcefully shut down and freeze background processes that bypass standard limits.',
    communityPraise: 'Highly praised in the root community for reclaiming battery life on budget processors (like the Helio G85) by halting aggressive trackers.',
    linkUrl: 'https://github.com/Tencent/Thanox',
    iconName: 'settings_suggest',
  ),
  RootApp(
    title: 'Hide My Applist (HMA)',
    description: 'An LSPosed module to hide selected apps (like root tools or managers) from the eyes of scanning applications.',
    category: 'Security & Privacy',
    whatIsIt: 'A system hook utility that intercepts packages querying calls, returning a dummy blacklisted list.',
    whyRoot: 'Hooks directly into the package manager service at runtime via LSPosed to intercept and spoof application checks.',
    communityPraise: 'Essential for running banking apps. It prevents them from seeing that you have Magisk, Termux, or custom recovery folders present.',
    linkUrl: 'https://github.com/Dr-TSNG/Hide-My-Applist',
    iconName: 'block',
  ),
  RootApp(
    title: 'MiXplorer',
    description: 'The ultimate, highly customized file explorer featuring built-in SQLite, text editors, and root browser access.',
    category: 'System Utilities',
    whatIsIt: 'A file manager designed for absolute access to storage, servers, and system drives.',
    whyRoot: 'Needs root permissions to access secure system root directories (like /system, /data/data) and modify configuration permissions.',
    communityPraise: 'Widely praised as the most powerful file explorer in existence. It has native archive extraction, server mounts, and terminal shortcuts.',
    linkUrl: 'https://mixplorer.com/',
    iconName: 'folder',
  ),
  RootApp(
    title: 'App Manager',
    description: 'A full-featured, open-source app inspector, tracker remover, and block manager.',
    category: 'System Utilities',
    whatIsIt: 'A utility to dissect installed applications, view components, permissions, and app ops.',
    whyRoot: 'Uses root to disable specific app components (activities/services), bypass system App Ops restrictions, and force-freeze bloatware.',
    communityPraise: 'Highly praised by privacy advocates for its forensic detail. Lets you identify and disable specific ad tracking services built into apps.',
    linkUrl: 'https://github.com/MuntashirAkon/AppManager',
    iconName: 'construction',
  ),
  RootApp(
    title: 'ColorBlendr',
    description: 'An open-source personalization engine to override Material You dynamic system colors.',
    category: 'UI Customization',
    whatIsIt: 'A theme tool that intercepts system monetization engine color generations.',
    whyRoot: 'Requires root access to overwrite read-only system color configurations and overlay dynamic palettes.',
    communityPraise: 'Praiseworthy for providing pure, customized aesthetics. Let\'s you set customized system hues without installing third-party ROMs.',
    linkUrl: 'https://github.com/Bnyro/ColorBlendr',
    iconName: 'palette',
  ),
  RootApp(
    title: 'CorePatch',
    description: 'An LSPosed module to relax package signature checks, enabling downgrades and modded installs.',
    category: 'System Framework',
    whatIsIt: 'A signature validation bypass tool that edits OS package manager routines in memory.',
    whyRoot: 'Requires LSPosed system hooking to bypass core Android package signature verification codes.',
    communityPraise: 'A staple for app modders. Allows you to install modified versions of apps directly over official ones without losing user data.',
    linkUrl: 'https://github.com/LSPosed/CorePatch',
    iconName: 'extension',
  ),
  RootApp(
    title: 'Termux',
    description: 'A powerful terminal emulator and Linux environment for Android. Access standard command-line tools and shell scripts.',
    category: 'Terminal & CLI',
    whatIsIt: 'A terminal shell interface that replicates a Linux command line directly on Android.',
    whyRoot: 'Using "su" in Termux bypasses all Android user space containment, allowing you to run standard Linux administrator utilities.',
    communityPraise: 'Essential for shell scripting and local coding. Highly praised for letting you control raw device states wirelessly or locally.',
    linkUrl: 'https://github.com/termux/termux-app/releases',
    iconName: 'terminal',
  ),
  RootApp(
    title: 'AdAway',
    description: 'A system-wide ad blocker that modifies the device hosts file to block ads in all apps.',
    category: 'System Utilities',
    whatIsIt: 'A lightweight blocker that routes known ad-server domains to a dead-end IP address.',
    whyRoot: 'Requires root permission to overlay the system "/system/etc/hosts" file which is read-only by default.',
    communityPraise: 'A timeless staple. Because it operates at the hosts level, it uses zero battery and blocks ads across games, apps, and browsers.',
    linkUrl: 'https://adaway.org/',
    iconName: 'block',
  ),
  RootApp(
    title: 'Swift Backup',
    description: 'A swift, cloud-integrated backup manager that backs up your APKs, internal user data, and system configurations.',
    category: 'Backups',
    whatIsIt: 'A premium backup application designed specifically for rooted Android setups.',
    whyRoot: 'Uses root permissions to access and package private app data folders (/data/data) that standard tools cannot read.',
    communityPraise: 'The standard for backing up app states. Lets you restore social apps, configurations, and logins instantly without typing passwords.',
    linkUrl: 'https://play.google.com/store/apps/details?id=parts.swift.backup',
    iconName: 'backup',
  ),
  RootApp(
    title: 'SmartPack Kernel Manager',
    description: 'An advanced kernel manager that lets you tune CPU/GPU frequencies, manage memory, and set charging limits.',
    category: 'Performance Tuning',
    whatIsIt: 'A tuning utility to read and write values directly inside kernel variables.',
    whyRoot: 'Requires root to modify system kernel parameters inside "/sys" that govern CPU profiles and charging bounds.',
    communityPraise: 'Highly praised open-source utility for kernel tuning. Essential for maximizing battery life or hardware testing on your Motorola G24.',
    linkUrl: 'https://github.com/SmartPack/SmartPack-Kernel-Manager/releases',
    iconName: 'settings_suggest',
  ),
  RootApp(
    title: 'LSPosed (Zygisk)',
    description: 'A modern Xposed framework implementation built on top of Zygisk for runtime system hooking.',
    category: 'System Framework',
    whatIsIt: 'A framework loader that injects customization modules directly into active system processes.',
    whyRoot: 'Requires system-level loader hooks and Zygisk integration to inject custom code into Android\'s system server.',
    communityPraise: 'The backbone of modern Android UI modification. It lets you customize layouts, lock screens, and permissions without rewriting system files.',
    linkUrl: 'https://github.com/LSPosed/LSPosed/releases',
    iconName: 'extension',
  ),
];
