import '../../models/tool.dart';

const List<Tool> toolsList = [
  Tool(
    title: 'Termux',
    description: 'A powerful terminal emulator and Linux environment for Android. Access standard command-line tools, shell scripts, and package managers without root, and unlock full power with root privileges.',
    category: 'Terminal & CLI',
    linkUrl: 'https://github.com/termux/termux-app/releases',
    iconName: 'terminal',
    whatIsIt: 'An app that gives you a local Linux command-line shell interface directly on your Android phone, similar to a Terminal window on a desktop computer.',
    whyDoIWantIt: 'It allows you to run powerful scripts, command line commands, compile software, use secure ssh terminals, and manage device files directly without needing a PC.',
  ),
  Tool(
    title: 'Kali NetHunter',
    description: 'An open-source penetration testing platform for Android devices. Access the Kali toolset (nmap, Metasploit, Wifite, etc.) directly on your phone.',
    category: 'Security Testing',
    linkUrl: 'https://www.kali.org/docs/nethunter/',
    iconName: 'security',
    whatIsIt: 'A specialized suite of cybersecurity and penetration testing tools compiled to run inside an isolated Linux environment on your phone.',
    whyDoIWantIt: 'It turns your Motorola G24 into a portable hacking and security auditing station to test wireless networks, scan server ports, and audit hardware security.',
  ),
  Tool(
    title: 'Tool-X',
    description: 'An automated installer for over 370 hacking tools in Termux. Perfect for quickly setting up security testing utilities on a clean terminal.',
    category: 'Security Testing',
    linkUrl: 'https://github.com/Rajkumarsidus/Tool-X',
    iconName: 'build',
    whatIsIt: 'A terminal installer script that simplifies searching and installing hundreds of security analysis packages directly into Termux.',
    whyDoIWantIt: 'Manually downloading and compiling hacking utilities is tedious. Tool-X lets you install complete categories of tools with a single click.',
  ),
  Tool(
    title: 'AdAway',
    description: 'A system-wide open-source ad blocker that uses the hosts file to block ads in all apps and browsers. Lightweight and uses zero battery.',
    category: 'System Utility',
    linkUrl: 'https://adaway.org/',
    iconName: 'block',
    whatIsIt: 'An ad blocker that works by altering your phone\'s system host file to point ad servers to a dead-end IP address (localhost).',
    whyDoIWantIt: 'Unlike browser extensions, it blocks ads everywhere—inside free apps, video players, and games—without using any extra RAM or battery.',
  ),
  Tool(
    title: 'Swift Backup',
    description: 'A premium-tier backup manager that backs up your APKs, user data, app configs, Wi-Fi networks, and SMS messages. Highly recommended for rooted systems.',
    category: 'Backups',
    linkUrl: 'https://play.google.com/store/apps/details?id=parts.swift.backup',
    iconName: 'backup',
    whatIsIt: 'An advanced backup utility that utilizes root permissions to copy the private internal data directories of your applications.',
    whyDoIWantIt: 'Standard Android backups only save app list files. Swift Backup copies the actual data, meaning you can restore apps and be automatically logged in and configured.',
  ),
  Tool(
    title: 'SmartPack Kernel Manager',
    description: 'An advanced kernel manager that lets you tune CPU and GPU governors, manage memory (low memory killer), monitor performance, and control battery charging limits.',
    category: 'Performance',
    linkUrl: 'https://github.com/SmartPack/SmartPack-Kernel-Manager/releases',
    iconName: 'settings_suggest',
    whatIsIt: 'A manager app that lets you view and alter variables on the running Linux kernel of your phone.',
    whyDoIWantIt: 'You can adjust CPU frequencies to save battery, set charging limits to protect battery health, and tweak low-memory behavior to prevent app lag.',
  ),
  Tool(
    title: 'LSPosed (Zygisk)',
    description: 'A modern Xposed framework implementation built on top of Zygisk. Allows you to hook into system methods to tweak device UI and behaviors without modifying system files.',
    category: 'System Framework',
    linkUrl: 'https://github.com/LSPosed/LSPosed/releases',
    iconName: 'extension',
    whatIsIt: 'A framework overlay that lets you inject code blocks directly into operating system classes and app runtimes dynamically.',
    whyDoIWantIt: 'Allows you to customize status bars, force apps to permit screenshots, modify hardware signatures to bypass tracking, and add hardware key actions.',
  ),
  Tool(
    title: 'Neo Store',
    description: 'A modern, beautiful, and secure F-Droid client for downloading open-source Android apps. Provides clean UI and automatic background updates.',
    category: 'App Store',
    linkUrl: 'https://github.com/NeoApplications/Neo-Store/releases',
    iconName: 'shop',
    whatIsIt: 'An alternative app store that hosts only free and open-source software (F-Droid repository).',
    whyDoIWantIt: 'Allows you to download privacy-respecting, root-friendly, and open-source applications without telemetry tracking or needing a Google Account.',
  ),
  Tool(
    title: 'Canta',
    description: 'An open-source uninstaller app that uses Shizuku to uninstall any system app and bloatware without root, but runs even faster with root permissions.',
    category: 'System Utility',
    linkUrl: 'https://github.com/samolego/Canta/releases',
    iconName: 'delete_forever',
    whatIsIt: 'An uninstaller utility that bypasses standard Android user limits to delete pre-installed system apps (bloatware).',
    whyDoIWantIt: 'Allows you to safely uninstall default Facebook services, manufacturer bloatware, and Google tracking services, freeing up memory and CPU.',
  ),
  Tool(
    title: 'MTKClient',
    description: 'A powerful tool to bypass bootloader security and read/write partitions on MediaTek devices at the BootROM level. Keep this on your PC for emergency recovery.',
    category: 'PC Tool',
    linkUrl: 'https://github.com/bkerler/mtkclient',
    iconName: 'computer',
    whatIsIt: 'A specialized computer program that interfaces directly with MediaTek microcontrollers before the bootloader even runs.',
    whyDoIWantIt: 'If your device boot loops or gets "soft-bricked" and refuses to turn on, MTKClient on your PC lets you read/write device memory partitions to repair the system.',
  ),
];
